config/routes.rb
Rails.application.routes.draw do
  root 'home#search'

  post :search_champion, to: 'search#search_champion'

end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def search_champion
    @option = SearchOption.find_by(name: params[:search_option])
    redirect_to root_path if @option.nil?

    @region = Region.find_by(key: params[:region])

    if @option.ordering == 'champion'
      @result = HighestStat.by_region(@region)
        .by_champ_name(@option.associated_stat).first
    else
      @result = HighestStat.by_region(@region)
        .order(@option.order_query).first
    end

    render :results
  end
end

app/helpers/search_helper.rb
module SearchHelper
  #def search_options
    #options = SearchOption.all.shuffle
  #end

  def to_decimal_non_zero_value(number, decimals = 1)
    result = "%.10g" % ("%.#{decimals}f" % number)
    if result.to_f == 0 && decimals < 8
      return to_decimal_non_zero_value(number, decimals + 1) 
    else
      return result
    end
  end
end

app/views/search/_navbar.html.slim
nav.navbar.navbar-default.navbar-results role="navigation"
  .container-fluid
    .navbar-header
      = link_to root_path do
        = image_tag asset_path('logo.png'), class: 'navbar-logo'

    .collapse.navbar-collapse
      .col-sm-5.col-md-5
        = form_tag search_champion_path, id: 'search-form', class: 'form-inline search-form-navbar', onkeypress: 'return event.keyCode != 13;'
          = render 'partial/search_bar'

          = select_tag 'region', options_for_select(Region.for_select, @region.nil? ? nil : @region.key), include_blank: 'Global', class: 'form-control select-region'

      = render 'partial/links'
      

app/views/search/results.html.slim
= render 'navbar'

.container-fluid.no-margin
  .content.shadow-rectangle
    .champ-info
      h4 Your best pick is
      .row
        .col-sm-2
          img.sprite src="#{@result.champion.sprite}"
        .col-sm-10
          h1.champ-name = @result.champion.name
          p = @result.champion.title

      .row
        h3.explanation = @option.explanation_for(@result.champion.name)

    .title
      h2.left Stats
      a.icon.inverse href="#" data-toggle="tooltip" data-placement="top" data-original-title="This data represent the average stats for this champion. It was collected from #{MatchDetail.count} random URF matches."
        i.glyphicon.glyphicon-question-sign

    .scrollable
      table.table
        - @result.stats_names.each do |stat_name|
          tr
            td.yellow = stat_name.humanize
            - if(stat_name == "wins" or stat_name == "loses")
              td = number_to_percentage("%.1f" % (@result[stat_name] * 100), precision: 0)
            - else
              td = to_decimal_non_zero_value(@result[stat_name])
              /td = "%.10g" % ("%.2f" % @result[stat_name])

= put_background_image(@result.champion.image, "top")